- id: '1548543406979'
  alias: WOL-Promox-WD
  trigger:
  - minutes: /1
    platform: time_pattern
  condition:
  - condition: state
    entity_id: switch.proxmox
    state: 'off'
  - condition: state
    entity_id: binary_sensor.portable
    state: 'on'
  action:
  - alias: ''
    data:
      entity_id: switch.proxmox
    service: switch.turn_on
- id: '1548543406979'
  alias: WOL-Promox-WE
  trigger:
  - at: '11:30'
    platform: time
  condition:
  - condition: state
    entity_id: switch.proxmox
    state: 'off'
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - alias: ''
    data:
      entity_id: switch.proxmox
    service: switch.turn_on
- id: '1548547721240'
  alias: Raspotify-Start
  trigger:
  - at: '18:30'
    platform: time
  condition:
  - condition: state
    entity_id: switch.raspotify
    state: 'off'
  action:
  - alias: ''
    data:
      entity_id: switch.raspotify
    service: switch.turn_on
- id: '1548548454832'
  alias: Raspotify-Stop
  trigger:
  - at: 01:00
    platform: time
  condition:
  - condition: state
    entity_id: automation.raspotify
    state: 'on'
  action:
  - data:
      entity_id: switch.raspotify
    service: switch.turn_off
- id: '1548688510506'
  alias: Neige Incoming
  trigger:
  - above: '1'
    below: '101'
    entity_id: sensor.villeurbanne_snow_chance
    for: 00:15
    platform: numeric_state
  condition: []
  action:
  - data:
      message: 'Snow Probability : {{ states.sensor.villeurbanne_snow_chance.state
        }}'
      title: Winter is coming
    service: notify.email_kirby
- id: '1548688675473'
  alias: Rain Incoming
  trigger:
  - above: '10'
    below: '101'
    entity_id: sensor.villeurbanne_rain_chance
    for: 00:15
    platform: numeric_state
  condition: []
  action:
  - data:
      message: 'Rain Probability : {{ states.sensor.villeurbanne_rain_chance.state
        }}'
      title: Rain is coming
    service: notify.email_kirby
- id: '1548694944674'
  alias: home.hyrule.ovh changed
  trigger:
  - entity_id: sensor.home
    platform: state
  condition: []
  action:
  - data:
      message: ''
      title: Public IP changed to {{ states.sensor.home.state }}
    service: notify.email_kirby
- id: '1550611366131'
  alias: WoL-Fixe
  trigger:
  - hours: '*'
    minutes: '''/1'''
    platform: time_pattern
    seconds: '*'
  condition:
  - condition: state
    entity_id: binary_sensor.portable
    state: 'off'
  action:
  - data:
      entity_id: switch.fixe
    service: switch.turn_on
- id: '1550611422711'
  alias: WoL-Fixe
  trigger: []
  condition: []
  action: []
- id: '1550754446981'
  alias: Cert-expired
  trigger:
  - below: '15'
    entity_id: sensor.cert_main
    platform: numeric_state
  - below: '15'
    entity_id: sensor.cert_smtp
    platform: numeric_state
  - below: '15'
    entity_id: sensor.cert_home
    platform: numeric_state
  condition: []
  action:
  - data_template:
      message: 'Cert renewal issue for {{ states[trigger.to_state.domain][trigger.to_state.object_id].name }} :
        {{ states[trigger.to_state.domain][trigger.to_state.object_id].state }} days remaining'
      title: Certificate renewal failure
    service: notify.email_kirby
