- id: '1548694944674'
  alias: home.hyrule.ovh changed
  trigger:
  - entity_id: sensor.home
    platform: state
  condition: []
  action:
  - data:
      message: ''
      title: Public IP changed to {{ states.sensor.home.state }}
    service: notify.email_kirby
- id: '1550754446981'
  alias: Cert-expired
  trigger:
  - below: '15'
    entity_id: sensor.cert_main
    platform: numeric_state
  - below: '15'
    entity_id: sensor.cert_smtp
    platform: numeric_state
  - below: '15'
    entity_id: sensor.cert_home
    platform: numeric_state
  condition: []
  action:
  - data_template:
      message: 'Cert renewal issue for {{ states[trigger.to_state.domain][trigger.to_state.object_id].name
        }} : {{ states[trigger.to_state.domain][trigger.to_state.object_id].state
        }} days remaining'
      title: Certificate renewal failure
    service: notify.email_kirby
- id: 41171191b1914c5dacdbfbaeef735399
  alias: Proxmox
  trigger:
  - at: '10:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - data:
      entity_id: switch.proxmox
    service: switch.turn_on
- id: d836acb077534690a54dac068df49e59
  alias: Proxmox2
  trigger:
  - at: '11:30:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - data:
      entity_id: switch.proxmox
    service: switch.turn_on
- alias: light-extinction
  trigger:
  - at: '00:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
    entity_id: group.all_lights
    service: light.turn_off
