- platform: discogs
  token: !secret discogs_token
- platform: dnsip
  hostname: !secret dns_home
  name: home
  resolver: 1.1.1.1
- platform: dnsip
  hostname: !secret dns_main
  name: main
  resolver: 1.1.1.1
################################
#
#           Disabled haveibeenpwen due to 403 erros
#	    2019/01/27
#
################################
#- platform: haveibeenpwned
#  email: !secret haveibeenpwned_email
- platform: pi_hole
  host: !secret pihole_host
  monitored_conditions:
    - ads_blocked_today
    - dns_queries_today
    - domains_being_blocked
    - unique_domains
    - unique_clients
    - clients_ever_seen
- platform: waqi
  token: !secret waqi_api
  locations: !secret waqi_locations
- platform: cert_expiry
  host: !secret cert_main
  name: !secret cert_main_name
- platform: cert_expiry
  host: !secret cert_hass
  name: !secret cert_hass_name
