- platform: wake_on_lan
  name: "Proxmox"
  mac_address: "00:01:2E:49:76:36"
  host: "192.168.1.150"
  broadcast_address: "192.168.1.255"
- platform: wake_on_lan
  name: "Fixe"
  mac_address: "D0:50:99:45:F2:5C"
  host: "192.168.1.100"
  broadcast_address: "192.168.1.255"
- platform: command_line
  switches:
    raspotify:
      command_on: "sudo systemctl start raspotify"
      command_off: "sudo systemctl stop raspotify"
      command_state: "sudo systemctl status raspotify"
- platform: command_line
  switches:
    emby:
      command_off: '/home/homeassistant/.homeassistant/scripts/proxmox stop vm 107'
      command_on: '/home/homeassistant/.homeassistant/scripts/proxmox start vm 107'
      command_state: '/home/homeassistant/.homeassistant/scripts/proxmox status vm 107'
      friendly_name: Emby
    sharing:
      command_off: '/home/homeassistant/.homeassistant/scripts/proxmox stop vm 108'
      command_on: '/home/homeassistant/.homeassistant/scripts/proxmox start vm 108'
      command_state: '/home/homeassistant/.homeassistant/scripts/proxmox status vm 108'
      friendly_name: Sharing
    jukebox:
      command_off: '/home/homeassistant/.homeassistant/scripts/proxmox stop vm 103'
      command_on: '/home/homeassistant/.homeassistant/scripts/proxmox start vm 103'
      command_state: '/home/homeassistant/.homeassistant/scripts/proxmox status vm 103'
      friendly_name: Jukebox
    pihole:
      command_off: '/home/homeassistant/.homeassistant/scripts/proxmox stop vm 111'
      command_on: '/home/homeassistant/.homeassistant/scripts/proxmox start vm 111'
      command_state: '/home/homeassistant/.homeassistant/scripts/proxmox status vm 111'
      friendly_name: Pihole
    mineos:
      command_off: '/home/homeassistant/.homeassistant/scripts/proxmox stop vm 122'
      command_on: '/home/homeassistant/.homeassistant/scripts/proxmox start vm 122'
      command_state: '/home/homeassistant/.homeassistant/scripts/proxmox status vm 122'
      friendly_name: MineOS
