resources:
  - url: /local/discogs-card.js
    type: module

title: Home
views:
  - title : Misc
    path: "default_view"
    cards: !include lovelace/views/misc.yaml
  - title: "Meteo"
    cards: !include lovelace/views/meteo.yaml
  - title: "Network"
    cards: !include lovelace/views/network.yaml
  - title: "Graphs"
    cards: !include lovelace/views/graphs.yaml
